first try

diff --git a/.github/workflows/deploy_app_to_expo.yml b/.github/workflows/deploy_app_to_expo.yml
--- a/.github/workflows/deploy_app_to_expo.yml
+++ b/.github/workflows/deploy_app_to_expo.yml
@@ -30,12 +30,12 @@ jobs:
             fi
             echo "::set-output name=ready::${ready}"
 
-        - name: PR is not ready
-          if: steps.check_ready.outputs.ready != 'approved'
-          run: |
-            echo "PR is not ready for deployment; It is in "${{steps.check_ready.outputs.ready}} state". Exiting workflow."
-            echo "::error::PR is not ready for deployment."
-            exit 1
+        # - name: PR is not ready
+        #   if: steps.check_ready.outputs.ready != 'approved'
+        #   run: |
+        #     echo "PR is not ready for deployment; It is in "${{steps.check_ready.outputs.ready}} state". Exiting workflow."
+        #     echo "::error::PR is not ready for deployment."
+        #     exit 1
 
         - name: Use Node.js
           uses: actions/setup-node@v2
@@ -68,13 +68,19 @@ jobs:
         - name: Install dependencies
           run: npm install @config-plugins/react-native-ble-plx
 
-        - name: Publish Update to EAS
-          run: eas update --branch ${{ github.event.pull_request.head.ref }} --message "Update triggered by PR ${{ github.event.pull_request.number }}"
+        - name: Publish Update to EAS and save output
+          run: eas update --branch ${{ github.event.pull_request.head.ref }} --message "Update triggered by PR ${{ github.event.pull_request.number }}" | tee output.txt
   
+        - name: Extract Android update ID
+          id: extract_id
+          run: |
+            ANDROID_UPDATE_ID=$(grep "Android update ID" output.txt | awk '{print $4}')
+            echo "::set-output name=android_update_id::${ANDROID_UPDATE_ID}"
+
         - name: Add comment to JIRA issue
           run: |
             # Construct the Expo preview channel URL
-            EXPO_URL="exp://exp.host/@dumax_st/ELD?release-channel=${{ github.event.pull_request.head.ref }}"
+            EXPO_URL="exp://u.expo.dev/update/${{ steps.extract_id.outputs.android_update_id }}"
             curl -X POST -H "Content-Type: application/json" \
               -d '{
                 "body": {
