Commented out code for PR readiness check and cache clearing

diff --git a/.github/workflows/deploy_app_to_expo.yml b/.github/workflows/deploy_app_to_expo.yml
--- a/.github/workflows/deploy_app_to_expo.yml
+++ b/.github/workflows/deploy_app_to_expo.yml
@@ -30,12 +30,12 @@ jobs:
             fi
             echo "::set-output name=ready::${ready}"
 
-        - name: PR is not ready
-          if: steps.check_ready.outputs.ready != 'approved'
-          run: |
-            echo "PR is not ready for deployment; It is in "${{steps.check_ready.outputs.ready}} state". Exiting workflow."
-            echo "::error::PR is not ready for deployment."
-            exit 1
+        # - name: PR is not ready
+        #   if: steps.check_ready.outputs.ready != 'approved'
+        #   run: |
+        #     echo "PR is not ready for deployment; It is in "${{steps.check_ready.outputs.ready}} state". Exiting workflow."
+        #     echo "::error::PR is not ready for deployment."
+        #     exit 1
 
         - name: Use Node.js
           uses: actions/setup-node@v2
@@ -52,11 +52,9 @@ jobs:
             FULL_STRING="${{ github.event.pull_request.head.ref }}"
             JIRAISSUEID=$(echo $FULL_STRING | cut -d'-' -f1,2)
             echo "JIRAISSUEID=$JIRAISSUEID" >> $GITHUB_ENV
+
         - name: Install Expo CLI
           run: npm install -g expo-cli
-          
-        - name: Clear CACHE 
-          run: npx react-native start --reset-cache
           
         - name: Expo Login
           env:
