Remove unnecessary code and add PR readiness check

diff --git a/.github/workflows/deploy_app_to_expo.yml b/.github/workflows/deploy_app_to_expo.yml
--- a/.github/workflows/deploy_app_to_expo.yml
+++ b/.github/workflows/deploy_app_to_expo.yml
@@ -18,10 +18,6 @@ jobs:
         steps:
         - uses: actions/checkout@v2
 
-        
-        - name: Echo REACT_NATIVE_ELD_API
-          run: echo ${{ vars.REACT_NATIVE_ELD_API }}   
-
         - name: Check if PR is ready
           id: check_ready
           run: |
@@ -34,12 +30,12 @@ jobs:
             fi
             echo "::set-output name=ready::${ready}"
 
-        # - name: PR is not ready
-        #   if: steps.check_ready.outputs.ready != 'approved'
-        #   run: |
-        #     echo "PR is not ready for deployment; It is in "${{steps.check_ready.outputs.ready}} state". Exiting workflow."
-        #     echo "::error::PR is not ready for deployment."
-        #     exit 1
+        - name: PR is not ready
+          if: steps.check_ready.outputs.ready != 'approved'
+          run: |
+            echo "PR is not ready for deployment; It is in "${{steps.check_ready.outputs.ready}} state". Exiting workflow."
+            echo "::error::PR is not ready for deployment."
+            exit 1
 
         - name: Use Node.js
           uses: actions/setup-node@v2
